name: Run CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMG_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Log in to the Container registry
        if: ${{ github.event_name != 'pull_request' || ! github.event.pull_request.head.repo.fork }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Short Commit SHA
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Build Image
        id: build-image
        run: |
          #!/usr/bin/env bash
          set -euo pipefail
          make IMG=${IMG} docker-build
        shell: bash
        env:
          IMG: ${{ env.REGISTRY }}/${{ env.IMG_NAME }}:${{ steps.vars.outputs.sha_short }}

      - name: Push Image
        if: ${{ github.event_name != 'pull_request' || ! github.event.pull_request.head.repo.fork }}
        run: |
          #!/usr/bin/env bash
          set -euo pipefail
          make IMG=${IMG} docker-push
        shell: bash
        env:
          IMG: ${{ env.REGISTRY }}/${{ env.IMG_NAME }}:${{ steps.vars.outputs.sha_short }}